### ISSUE TITLE
Resizing the main application Window causes input problem

### ISSUE THREAD

**Issue by astrofra** [harfang3d/harfang-gui#11]
Resizing the main application Window causes several problems : 
 * the content is stretched
 * the inputs are 'off'

The solution should be to tell harfang to resize the rendering area & the input area according to the new window's size.
This should be done in the samples themself, it will improve the perception of the library by new users.

**Comment by ErkMkd** [comment]
Just use the `RenderResetToWindow` HARFANG function.
