### ISSUE TITLE
Add alignment option to widgets

### ISSUE THREAD

**Issue by Romainhj** [harfang3d/harfang-gui#26]
Add alignment presets to control widget positioning:
- center
- top
- bottom
- left
- right
- top-right
- top-left
- bottom-right
- bottom-left

Avoids having to use offset values to counter the default top-left position anchor during scale animations.

**Comment by ErkMkd** [comment]
-Added optional align method entry to widgets (default is HGUIAF_CENTER)
-Modified auto positionment system
-Added "set_inner_line_size" function to set space between widgets in same line
-Widget["offset"] is now reserved for alignment computation.
