### ISSUE TITLE
< > symbols don't show up in buttons

### ISSUE THREAD

**Issue by Arvolder** [harfang3d/harfang-gui#28]
May have to do with the font, when running either of those lines of codes, the button appears empty as only the space characters show up
if hgui.button(" < "):
if hgui.button(" > "):

**Comment by astrofra** [comment]
Thanks for reporting this issue. 
It doesn't seem to be a problem with the font init code (I checked the list of glyphs in the init and your missing characters are here), so it _might_ a problem with the font itself.

A test with an alternate font file (a larget TTF) could help to pin point the exact source of this problem.

**Comment by ErkMkd** [comment]
I've made a recent update:
![image](https://user-images.githubusercontent.com/11889393/190359400-26b7e091-c806-48a6-ae1d-37d2665f25a9.png)

**Comment by ErkMkd** [comment]
Perhaps if you pull to your local repo ?
