### ISSUE TITLE
Add 'Label' functionnality to button_image widget

### ISSUE THREAD

**Issue by Romainhj** [harfang3d/harfang-gui#29]
Add the possibility to stack an icon + text in one button such as seen below :

![image](https://user-images.githubusercontent.com/113510766/190385934-52a631fd-00f8-44f6-a616-b732737c7ad6.png)

Improve button_image widget functionnality with an optional text label.

**Comment by ErkMkd** [comment]
just specifiy "show_label = True / False" for image_button, check_box and input_text widgets.
